version: "3.7"

services:
#------------------ mariadb ----------------------#
  mariadb:
      image: "mariadb:latest"
      restart: 'always'
      volumes:
        - "db-data:/var/lib/mysql/data"
        - "./db-dump:/docker-entrypoint-initdb.d"
      environment:
          MYSQL_USER: "admin"
          MYSQL_PASSWORD: "password"
          MARIADB_ROOT_PASSWORD: "password"
          MYSQL_TCP_PORT: 3307
      ports:
         - '3307:3307'

  back:
      container_name: back-service
      build: ./dashboard-back
      ports:
        - target: 8080
          published: 8080
          mode: host
      volumes:
        - "./dashboard-back:/app/src"
      depends_on:
        - mariadb

  front:
      container_name: front-service
      build: ./dashboard-front
      ports:
        - "3000:3000"
      volumes:
        - "./dashboard-front/src:/app/src"
        - "./dashboard-front/public:/app/public"

volumes:
  db-data:

