version: "3.7"

services:
#------------------ mariadb ----------------------#
  mariadb:
      image: "mariadb:latest"
      restart: 'always'
      ports:
        - '3307:3307'
      volumes:
        - "db-data:/var/lib/mysql/data"
        - "./db-dump:/docker-entrypoint-initdb.d"
      environment:
          MYSQL_USER: "admin"
          MYSQL_PASSWORD: "password"
          MARIADB_ROOT_PASSWORD: "password"
volumes:
  db-data: