version: "3.7"

services:
#------------------ mariadb ----------------------#
  mariadb:
      image: "mariadb:latest"
      restart: 'always'
      volumes:
        - "db-data:/var/lib/mysql/data"
        - "./db-dump:/docker-entrypoint-initdb.d"
      environment:
          MYSQL_USER: "admin"
          MYSQL_PASSWORD: "password"
          MARIADB_ROOT_PASSWORD: "password"
          MYSQL_TCP_PORT: 3307
      ports:
         - '3307:3307'

  back:
      build: ./dashboard-back
      ports:
        - "8080:8080"
      links:
        - mariadb:mariadb
      depends_on:
        - mariadb

  front:
      build: ./dashboard-front
      ports:
        - "3000:3000"

volumes:
  db-data:
